packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^20
  "@types/react": ^18
  "@types/react-dom": ^18
  "@biomejs/biome": ^1.9.3
  "@hookform/resolvers": ^3.9.0
  "@radix-ui/react-dropdown-menu": ^2.1.2
  "@radix-ui/react-icons": ^1.3.0
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-slot": ^1.1.0
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  eslint: ^8
  eslint-config-next: 14.2.15
  framer-motion: ^11.11.9
  geist: ^1.3.1
  next: 15.0.1
  next-themes: ^0.3.0
  postcss: ^8.4.47
  react: 18.3.1
  react-dom: 18.3.1
  react-hook-form: ^7.53.0
  sonner: ^1.5.0
  tailwind-merge: ^2.5.3
  tailwindcss: ^3.4.1
  tailwindcss-animate: ^1.0.7
  turbo: ^2.1.3
  typescript: ^5
  zod: ^3.23.8
